import "~/styles/globals.css";

import { type Metadata } from "next";
import { Cal_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "~/components/navbar";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "~/i18n/routing";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const calSans = Cal_Sans({
  weight: "400",
  subsets: ["latin"],
  fallback: ["sans-serif"],
});

type LayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: LayoutProps) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en" className={calSans.className} suppressHydrationWarning>
      <body className="bg-neutral-100 dark:bg-neutral-900">
        <main className="container mx-auto flex min-h-screen flex-col">
          <TRPCReactProvider>
            <NextIntlClientProvider>
              <ThemeProvider attribute={"class"}>
                <Navbar />
                {children}
              </ThemeProvider>
            </NextIntlClientProvider>
          </TRPCReactProvider>
        </main>
      </body>
    </html>
  );
}
